; ==============================================================
; --------------------------------------------------------------
; MD Platformer Core
;
;   by Mega Drive Developers Collective
;      AURORA FIELDS 2020/12
;
;   Miscellaneous hardware macros and equates
; --------------------------------------------------------------

HW_Version =		$A10001					; Mega Drive version register
HW_TMSS =		$A14000					; TMSS address

